// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/NoahWTeng/todo-api-go/src/infra/injectors"
)

// Injectors from wire.go:

func CreateNewApp() (*Container, error) {
	globalConfig, err := injectors.BaseConfigInjector()
	if err != nil {
		return nil, err
	}
	mux := injectors.RouterInjector()
	server := injectors.HttpServerInjector(globalConfig, mux)
	handler := injectors.MongodbProvider(globalConfig)
	services := injectors.UsersServicesProvider(handler)
	controllers := injectors.UsersControllersProvider(services)
	container := &Container{
		config:           globalConfig,
		httpServer:       server,
		router:           mux,
		mongodb:          handler,
		usersService:     services,
		usersControllers: controllers,
	}
	return container, nil
}
